services:
  postgres:
    image: postgres:15
    volumes: 
      - ./container:/data
      - ./container/script_me.sh:/docker-entrypoint-initdb.d/script_me.sh
    container_name: db_sql
    env_file:
      - envfile.env

